### PR TITLE
[Chore] Updated Errors to be Error Codes Utility Tool compatible

### PR DESCRIPTION
**Pull request by dhruv0000**
Signed-off-by: dhruv0000 <patel.4@iitj.ac.in>

**Description**
This PR updates Errors to be Error Codes Utility Tool :hammer_and_wrench: compatible.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Let's find a home other than root for these output files. @DelusionalOptimist can you define a standard location? // @mgfeller

**Comment by leecalcote** [comment]
@DelusionalOptimist let's see that the workflow to run the error code utility is propagated to all Meshery component repos.

**Comment by sayantan1413** [comment]
Hey @dhruv0000 I think I already solved it here https://github.com/meshery/meshery-nsm/pull/114 can you check it once?

**Comment by dhruv0000** [comment]
Sounds good. @sayantan1413 . I will close this PR.

**Comment by dhruv0000** [comment]
Lets get that merged.

**Comment by DelusionalOptimist** [comment]
> Let's find a home other than root for these output files. @DelusionalOptimist can you define a standard location? 

`helpers` is what we've been using in other repos (if someone can suggest a better name, please do)

> @DelusionalOptimist let's see that the workflow to run the error code utility is propagated to all Meshery component repos.

I think just some updates to make stuff "merge conflict proof" and we can start spreading it. Will do it by tom

**Pull request closed without merging**
