### PR TITLE
Updated the go version in github actions to 1.20

### PR DESCRIPTION
**Pull request by VaibhavMalik4187**
Switched to explicit declaration of the GO_VERSION variable in the actions files. Earlier the GO_VERSION was being read from the repository secrets.

Fixes: https://github.com/meshery/meshery-nsm/issues/147

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by VaibhavMalik4187** [comment]
@leecalcote Could you please review my pull request when you have a moment? Thank you!

**Comment by leecalcote** [comment]
> @leecalcote Could you please review my pull request when you have a moment? Thank you!

You bet. Although, I'll likely slow you down. Others that are faster and more knowledgeable than me: @nebula-aac @Revolyssup @abdullah1308 @hexxdump @Aisuko

**Comment by VaibhavMalik4187** [comment]
@leecalcote The runner is not able to find the analysis tools causing the jobs to fail, any idea why this is happening?

**Review by Aisuko — CHANGES_REQUESTED** [review]
@leecalcote Thank you.

Hi @VaibhavMalik4187, thanks for your contribution. Currently, we use 'golangci-lint' to check the code quality since we have upgraded to the version of Go. Please help us upgrade the CI to the latest like below. I believe these issues `CI cannot find tools should go away`.

https://github.com/meshery/meshery-operator/blob/e15e3bbd9186a5099abb6e2da6312efc86e7cd80/.github/workflows/approve-to-run-ci.yml#L10-L26

**Comment by VaibhavMalik4187** [comment]
> @leecalcote Thank you.
> 
> Hi @VaibhavMalik4187, thanks for your contribution. Currently, we use 'golangci-lint' to check the code quality since we have upgraded to the version of Go. Please help us upgrade the CI to the latest like below. I believe these issues `CI cannot find tools should go away`.
> 
> https://github.com/meshery/meshery-operator/blob/e15e3bbd9186a5099abb6e2da6312efc86e7cd80/.github/workflows/approve-to-run-ci.yml#L10-L26

Thanks for the pointer @Aisuko. I'll make the necessary changes and update the PR soon.

**Comment by VaibhavMalik4187** [comment]
@Aisuko please re-run the checks if you have some spare time, thanks!

**Comment by VaibhavMalik4187** [comment]
@Aisuko could you please trigger the tests if you have some spare time? Thanks a lot.

**Comment by leecalcote** [comment]
Checks triggered

**Comment by VaibhavMalik4187** [comment]
> Checks triggered

@leecalcote I looked into checks run and have also fixed all the errors related to the CI workflow. I had to move to go version 1.21 to get the changes working. Is this acceptable?

This PR is now ready for a deeper code review. Thanks!

**Comment by VaibhavMalik4187** [comment]
@nebula-aac, would you mind reviewing the code when you have a moment? Your feedback would be much appreciated. Thanks

**Comment by VaibhavMalik4187** [comment]
I'd also like to highlight that upgrading the linters and error checkers has reported the use of deprecated packages in some parts of the code. I'll be happy to eliminate those errors as a separate issue.

**Comment by VaibhavMalik4187** [comment]
@Aisuko please let me know if any changes are needed. Thanks!

**Comment by Revolyssup** [comment]
@VaibhavMalik4187 Please fix the failing lint tests.

**Comment by VaibhavMalik4187** [comment]
@Revolyssup I've fixed the failing lint tests.

**Review by Aisuko — APPROVED** [review]
LGTM

**Pull request merged**
